# Generated by Django 2.2.7 on 2019-11-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='bateria',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefono',
            name='precio',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefono',
            name='procesador',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
