# Generated by Django 2.2.7 on 2019-11-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20191117_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonoinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Agotado'), ('d', 'Disponible'), ('r', 'rebajado')], default='m', help_text='Estado del telefono', max_length=1),
        ),
    ]
